### ISSUE TITLE
weight parameter is incorrectly passed to leaflet

### ISSUE THREAD

**Issue by e-kotov** [environmentalinformatics-marburg/mapview#4] opened 2015-09-17 09:00 UTC
Hi, I have found a problem with the 'weight' argument of mapView(). When weight is passed as a variable or a manually constructed numeric vector, mapView() generates all the available objects multiple times and creates them with all the different weights passed to it. So basically, you can only currently pass numeric vector of length one to 'weight'. If one wants to attach a variable to 'weight', one needs to use leaflet functions directly.

p.s. appreciate your work on mapview!

Kind regards,
Egor

**Comment by tim-salabim** [comment] 2015-09-17 10:05
Hi Egor,
could you please provide a reproducible example that shows what you mean? As it is now, I don't even know what you kind of object you're talking about (points, lines, polygons?)

Cheers
Tim

**Comment by e-kotov** [comment] 2015-09-17 11:08
Sure, here's a code for what I am doing. Compare the output of mapView and more or less equivalent direct call to leaflet.

mapView produces every line with every line weight from the numeric vector, whereas leaflet produces the result as intended and expected.

```r
# install missing packages
# thanks to Pratik Patil for the code ( http://stackoverflow.com/a/29622385 )
# Specify the list of required packages to be installed and load    
Required_Packages = c("data.table", "sp", "geosphere", "scales")

Install_And_Load <- function(Required_Packages) {
        Remaining_Packages <- Required_Packages[!(Required_Packages %in% installed.packages()[,"Package"])]
        
        if(length(Remaining_Packages)) 
        {
                install.packages(Remaining_Packages)
        }
        for(package_name in Required_Packages)
        {
                library(package_name, character.only = T, quietly = F)
        }
}

# Call the Function
Install_And_Load(Required_Packages)

if ( sum(installed.packages() %in% "mapview") == 0 ) {
        library(devtools)
        install_github("environmentalinformatics-marburg/mapview")        
}

library(mapview)



# actual code for testing

runTest <- function() {
        
        n = 50
        
        # create a data table with random points
        x <- data.table( oLat = runif(n, min = 50, max = 69), # origin lat
                         oLon = runif(n, min = 30, max = 170), # origin lon
                         dLat = runif(n, min = 50, max = 69), # destination lat
                         dLon = runif(n, min = 30, max = 170), # destination lon
                         value = runif(n, min = 10, max = 1000)) # random migration values
        
        # create origin and destination points
        oX <- x
        coordinates(oX) = ~ oLon + oLat
        proj4string(oX) = CRS("+init=epsg:4326") # set coordinate system to WGS84
        dX <- x
        coordinates(dX) = ~ dLon + dLat
        proj4string(dX) = CRS("+init=epsg:4326") # set coordinate system to WGS84
        
        
        xPaths <- gcIntermediate(oX, dX, n = 50, addStartEnd = T, sp = T) # create great circle paths
        xPaths <- SpatialLinesDataFrame(sl = xPaths, data = x[ , .(value), ]) # attach the random migration values from original table
        
        xPaths@data$value_scaled <- rescale( log(xPaths@data$value), to = c(1,10)) # normalise the values to appropriate line widths
        xPaths@data$value_opacity <- rescale( log(xPaths@data$value), to = c(0.01,0.5)) # normalise the values to use for opacity
        
        # try to plot object with mapView
        mapView(xPaths, weight = xPaths@data$value_scaled, color = "red")
        # notice, how weight is interpreted, every line is plotted with every possible line weight
        
        # try to plot object with leaflet
        m = leaflet() %>%
                addTiles() %>%  # Add default OpenStreetMap map tiles
                addPolylines(data = xPaths, color = "red",
                             weight = xPaths@data$value_scaled, opacity = xPaths@data$value_opacity)
                             # weight = xPaths@data$value_scaled)
        m
        
}
```

**Comment by tim-salabim** [comment] 2015-09-18 08:59
Egor,
thanks for the comprehensive example! The issue should be fixed now (on develop branch). Can you please check and verify that it now behaves as expected. If it does, I will merge it into the master branch. 

You can install the develop branch with

library(devtools)
install_github("environmentalinformatics-marburg/mapview", ref = "develop")

In case you're interested, the problem was that I was over-complicating things by looping through every line segment individually and hence the weight vector that is passed is shorter than the actual number of  lines objects that are rendered and gets recycled. 

Best
Tim

**Comment by e-kotov** [comment] 2015-09-18 21:35
Hi Tim,

thanks, the code works now as expected, I think it is safe to merge your corrections.

By all means it was interesting to know what was wrong!

Kind regards,
Egor

**Comment by tim-salabim** [comment] 2015-09-19 08:03
Thanks Egor,
now merged into master

Tim

**Closed by tim-salabim** 2015-09-19 08:03 UTC
