### ISSUE TITLE
mapshot: Error: pandoc document conversion failed with error 97

### ISSUE THREAD

**Issue by adrfantini** [environmentalinformatics-marburg/mapview#45] opened 2016-11-02 13:59 UTC
I'm trying to save the map by using `mapshot`.
E.g.:

    m <- mapview(breweries91)
    mapshot(m, url = paste0(getwd(), "/map.html"))

But:

    pandoc: Could not find data file map_files/leaflet-0.7.7/
    Error: pandoc document conversion failed with error 97

I'm using pandoc 1.12.2.1 and the latest mapview and leaflet from Github.

**Comment by tim-salabim** [comment] 2016-11-02 14:10
I don't have any problems with this. What version of **htmltools** are you using?
My `sessionInfo()`:

```
R version 3.3.1 (2016-06-21)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 14.04.5 LTS

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=de_DE.UTF-8       
 [4] LC_COLLATE=en_US.UTF-8     LC_MONETARY=de_DE.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=de_DE.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
[10] LC_TELEPHONE=C             LC_MEASUREMENT=de_DE.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] raster_2.5-8       sp_1.2-3           mapview_1.2.6      leaflet_1.0.2.9003

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.7         magrittr_1.5        gdalUtils_2.0.1.7   munsell_0.4.3      
 [5] colorspace_1.2-6    viridisLite_0.1.3   lattice_0.20-34     foreach_1.4.3      
 [9] plyr_1.8.4          tools_3.3.1         parallel_3.3.1      webshot_0.3.2      
[13] rgdal_1.1-10        grid_3.3.1          R.oo_1.20.0         png_0.1-7          
[17] latticeExtra_0.6-28 htmltools_0.3.5     iterators_1.0.8     yaml_2.1.13        
[21] digest_0.6.10       RColorBrewer_1.1-2  htmlwidgets_0.7     R.utils_2.4.0      
[25] codetools_0.2-15    scales_0.4.0        R.methodsS3_1.7.1   stats4_3.3.1       
[29] jsonlite_1.1        satellite_0.3.0    
```

**Comment by adrfantini** [comment] 2016-11-02 14:32
R version 3.3.2 (2016-10-31)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 14.04.5 LTS

locale:
 [1] LC_CTYPE=en_US.utf8       LC_NUMERIC=C              LC_TIME=en_US.utf8
       LC_COLLATE=en_US.utf8
 [5] LC_MONETARY=en_US.utf8    LC_MESSAGES=en_US.utf8
 LC_PAPER=en_US.utf8       LC_NAME=C
 [9] LC_ADDRESS=C              LC_TELEPHONE=C
 LC_MEASUREMENT=en_US.utf8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] ggplot2_2.1.0      mapview_1.2.6      leaflet_1.0.2.9005 raster_2.5-8
    sp_1.2-3
[6] colorout_1.0-3

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.7         magrittr_1.5        gdalUtils_2.0.1.7
munsell_0.4.3       viridisLite_0.1.3
 [6] colorspace_1.2-6    lattice_0.20-34     foreach_1.4.3       plyr_1.8.4
         tools_3.3.2
[11] webshot_0.3.2       rgdal_1.1-10        grid_3.3.2
 gtable_0.2.0        R.oo_1.20.0
[16] png_0.1-7           latticeExtra_0.6-28 htmltools_0.3.5
iterators_1.0.8     yaml_2.1.13
[21] digest_0.6.10       RColorBrewer_1.1-2  base64enc_0.1-3
htmlwidgets_0.7     R.utils_2.4.0
[26] codetools_0.2-15    ncdf4_1.15          labeling_0.3
 scales_0.4.0        R.methodsS3_1.7.1
[31] stats4_3.3.2        jsonlite_1.0        satellite_0.2.0

**Comment by tim-salabim** [comment] 2016-11-02 18:15
I still have no clue what's happening here. I updated R and everything still works for me. Additionally, I don't understand the error message as it is clear that `file map_files/leaflet-0.7.7/` cannot be found because `mapshot` produces a selfcontained file. Can you try the following and see whether any of them work:

```
## without creation of above folder
htmlwidgets::saveWidget(m@map, 
                        file = paste0(getwd(), "/map.html"), 
                        selfcontained = TRUE)

## this is where the above folder should be created
htmlwidgets::saveWidget(m@map, 
                        file = paste0(getwd(), "/map.html"), 
                        selfcontained = FALSE)
```

**Comment by adrfantini** [comment] 2016-11-02 19:57
The folder actually exists, so I am also puzzled. Anyhow, the first command you listed fails with error 97, the second one does not fail and seems to reproduce a valid file.

**Comment by gisma** [comment] 2016-11-02 20:01
I can not reproduce the error. I have changed all versions of leaflet and mapview. Taking the develop branch the only location where  the physical string    
_leaflet-0.7.7_  still exist is in the deprecated leaflet.js from the also deprecated old big data implementation. 

my last sessioninfo is:
```
> sessionInfo()
R version 3.3.1 (2016-06-21)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.1 LTS

locale:
 [1] LC_CTYPE=de_DE.UTF-8       LC_NUMERIC=C               LC_TIME=de_DE.UTF-8       
 [4] LC_COLLATE=de_DE.UTF-8     LC_MONETARY=de_DE.UTF-8    LC_MESSAGES=de_DE.UTF-8   
 [7] LC_PAPER=de_DE.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
[10] LC_TELEPHONE=C             LC_MEASUREMENT=de_DE.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] mapview_1.2.6      leaflet_1.0.2.9005

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.7         raster_2.5-8        magrittr_1.5        devtools_1.12.0    
 [5] gdalUtils_2.0.1.7   munsell_0.4.3       colorspace_1.2-7    viridisLite_0.1.3  
 [9] lattice_0.20-34     R6_2.2.0            foreach_1.4.3       httr_1.2.1         
[13] plyr_1.8.4          tools_3.3.1         webshot_0.3.2       rgdal_1.1-10       
[17] grid_3.3.1          R.oo_1.20.0         png_0.1-7           latticeExtra_0.6-28
[21] git2r_0.15.0        withr_1.0.2         htmltools_0.3.5     iterators_1.0.8    
[25] yaml_2.1.13         digest_0.6.10       RColorBrewer_1.1-2  htmlwidgets_0.7    
[29] R.utils_2.4.0       codetools_0.2-15    curl_2.2            memoise_1.0.0      
[33] sp_1.2-3            scales_0.4.0        R.methodsS3_1.7.1   stats4_3.3.1       
[37] jsonlite_1.1        satellite_0.2.0 

```

**Comment by adrfantini** [comment] 2016-11-02 20:27
I do not know how I could help in debugging nor how to workaround this.
If there is any check or try I could do please do not hesitate to tell me!

2016-11-02 21:01 GMT+01:00 gisma <notifications@github.com>:

**Comment by tim-salabim** [comment] 2016-11-03 08:06
Do you use a custom `.Rprofile`?

**Comment by adrfantini** [comment] 2016-11-03 08:56
I do but it really contains only some basic definitions. The only unusual
thing is that I load the ackage colorout but I really do not see how that
would affect anything.

2016-11-03 9:06 GMT+01:00 tim-salabim <notifications@github.com>:

**Comment by tim-salabim** [comment] 2016-11-03 09:05
Was just wondering because of this:
https://github.com/yihui/knitr/issues/855

**Comment by tim-salabim** [comment] 2016-11-03 09:09
Are you on a dual boot machine and have your wd set to the ntfs windows drive? See this:

http://pandoc.error.97.errorwiki.org/

which says that error 97 is a windows error message

**Comment by adrfantini** [comment] 2016-11-03 10:18
Hi, I'm on a networked Unix system. The target FS is NFS. The local machines also have a Windows installation but I do no think this is relevant.

I also tried with my own laptop and cannot reproduce the issue. Can this be related to the pandoc version?
I have 1.12.2.1 on the problematic machine and 1.18 on my laptop.

**Comment by tim-salabim** [comment] 2016-11-03 10:21
Don't think so, I have `pandoc 1.12.2.1` and don't have the problem

**Comment by tim-salabim** [comment] 2016-11-03 10:45
I am beginning to believe that this is indeed a network drive issue. See this conversation:

https://github.com/rstudio/rmarkdown/issues/701

Also, I checked the sources of `saveWidget` which calls `htmlwidgets:::pandoc_self_contained_html` where things are written to the default system temp directory and only afterwards the selfcontained file is created and then copied to the specified output file (in the case of `mapshot` the `url`) path. Given that you don't seem to have problems on a local machine I guess this is likely the root of the issue. You may simply not have proper rights for the system root temp directory on the network share.

**Comment by adrfantini** [comment] 2016-11-07 14:53
Sorry for the delay.
I have tried again with a local FS but without any luck unfortunately, I still get the same error as before.

**Comment by adrfantini** [comment] 2016-11-07 15:58
​Yes I do not have any problem with my own Linux laptop, but then it's not
on the same network and may have different versions of the packages.​
My laptop is an up-to-date Arch machine, the machine giving problems
instead sports an old Ubuntu-based LTS.

I can confirm I can create the `tmpdir`.

**Comment by tim-salabim** [comment] 2016-11-07 16:20
Well, I don't think I can do much about this as it's clearly not a mapview issue. 
May be best to talk to your network admin.
I am closing this but feel free to post a solution in case you find a solution.l

**Closed by tim-salabim** 2016-11-07 16:20 UTC

**Comment by MarcusMorrisey** [comment] 2019-08-15 19:46
I just wanted to add that I also encountered this error when attempting to save to a networked drive and it was resolved by saving locally. Not a solution but a workaround.
